version: '3.8'
services:
  db:
    image: postgres:15
    container_name: trading_journal_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trading_journal
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: